// import 'dart:html';
import 'dart:math' as Math;
import 'package:asupan_app/models/models.dart';
import 'package:asupan_app/services/services.dart';
import 'package:asupan_app/ui/widgets/widgets.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:email_validator/email_validator.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:intl/intl.dart';
import 'package:logger/logger.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';

part 'frontpage.dart';
part 'login.dart';
part 'register.dart';
part 'mainmenu.dart';
part 'beranda.dart';
part 'datajk.dart';
part 'databerat.dart';
part 'bangun.dart';
part 'tidur.dart';
part 'riwayat.dart';
part 'alarm.dart';
part 'profil.dart';
part 'harian.dart';
